Dev => Master 2.3.0
nf-core/nascent pull request #185
Opened 2024-12-23 01:47 UTC by edmundmiller

~~Waiting for #184~~

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/nascent/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/nascent _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2025-01-08 08:07 UTC, sateeshperi approved these changes
Those local module & sub-wfs will need nf-test next

2025-01-08 08:07 UTC, sateeshperi commented on main.nf
> +params.homer_uniqmap = getGenomeAttribute('uniqmap')
```suggestion
params.fasta                    = getGenomeAttribute('fasta')
params.gtf                        = getGenomeAttribute('gtf')
params.gff                        = getGenomeAttribute('gff')
params.gene_bed            = getGenomeAttribute('bed12')
params.bwa_index           = getGenomeAttribute('bwa')
params.bwamem2_index = getGenomeAttribute('bwamem2')
params.dragmap              = getGenomeAttribute('dragmap')
params.bowtie2_index     = getGenomeAttribute('bowtie2')
params.hisat2_index        = getGenomeAttribute('hisat2')
params.star_index            = null
params.homer_uniqmap   = getGenomeAttribute('uniqmap')
```

2025-01-08 08:07 UTC, sateeshperi commented on nextflow.config
> +    // Depends on how you look at this one... But I figured most will ignore the negative
```suggestion
    // Depends on how you look at this one... But I figured most will ignore the negative
```
Could you clarify what you mean here ?

2025-01-10 16:22 UTC, vagkaratzas requested changes
Nice! Regular test runs smoothly under 10' and seems easy to follow. I left a couple of comments after a first pass. Will come back for more :D

2025-01-10 16:22 UTC, vagkaratzas commented on docs/output.md
>    - `*.coverage.stats.txt`: Coverage stats broken down by chromosome including %GC, pos/neg read coverage, total coverage, etc.
Similarly, I would change the asterisk to <samplename> everywhere else (when viable) in the output.md likewise.

2025-01-13 19:20 UTC, edmundmiller commented on assets/schema_input.json
>          "required": ["sample", "fastq_1"]
Thanks for catching that! Made a follow up issue for later.

2025-04-23 01:43 UTC, edmundmiller commented on main.nf
> +params.homer_uniqmap = getGenomeAttribute('uniqmap')
Just going to wait for nextflow lint. I've held out this long 😬

2025-04-23 01:44 UTC, edmundmiller commented on README.md
>  <!-- TODO nf-core: Describe the minimum required steps to execute the pipeline, e.g. how to prepare samplesheets.
See #96

2025-04-23 01:45 UTC, edmundmiller commented on nextflow.config
> +    // Depends on how you look at this one... But I figured most will ignore the negative
Just since it's a negative number, is the min -400 or -100? The docs called it min_ltprobb for groHMM.

2025-04-23 01:47 UTC, edmundmiller commented on conf/base.config
> +    // TODO nf-core: Check the defaults for all processes
Probably snuck in during a template update!

2025-04-23 01:49 UTC, edmundmiller commented on bin/grohmm_parametertuning.R
> +#!/usr/bin/env Rscript
Made a follow up issue for it!

2025-04-23 01:51 UTC, edmundmiller commented on docs/output.md
>    - `*.coverage.stats.txt`: Coverage stats broken down by chromosome including %GC, pos/neg read coverage, total coverage, etc.
I'm just following the standard in rnaseq. Is there somewhere in the docs that says otherwise?
https://nf-co.re/rnaseq/3.18.0/docs/output/#bedtools-and-bedgraphtobigwig

2025-04-23 08:13 UTC, maxulysse commented on CHANGELOG.md
> +- [7a4e356](https://github.com/nf-core/nascent/commit/7a4e356) - Update pipeline template to [nf-core/tools 3.1.1](https://github.com/nf-core/tools/releases/tag/3.1.1)
Why does the TEMPLATE updates have commit instead of PRs?

2025-04-23 08:20 UTC, maxulysse commented on nf-test.config
> +    triggers "nextflow.config", "nf-test.config", "conf/modules.config", "conf/test.config", "tests/nextflow.config"
I would add the json files as well

2025-04-23 08:21 UTC, maxulysse requested changes
Minor comments

2025-04-23 21:44 UTC, edmundmiller commented on CHANGELOG.md
> +- [7a4e356](https://github.com/nf-core/nascent/commit/7a4e356) - Update pipeline template to [nf-core/tools 3.1.1](https://github.com/nf-core/tools/releases/tag/3.1.1)
Because I broke the git history when I was young and naive and cared about that kind of stuff. 🙃

2025-04-23 21:44 UTC, edmundmiller commented on modules/local/grohmm/parametertuning/main.nf
> +    // array 10
I left it there as I'd like to implement it; the feature just wasn't working on the cluster. But I'll update the TODO!

2025-04-24 03:43 UTC, edmundmiller commented on tests/lib/UTILS.groovy
Nope!

2025-04-24 07:43 UTC, maxulysse commented
You have a couple of issues with the snapshots.
I would recommend to update the GHA to make it so that we can see more clearly which tests are failing, and properly differentiate the different tests that are being run

2025-05-04 12:53 UTC, maxulysse commented on CITATIONS.md
> +> Andrews, S. (2010). FastQC: A Quality Control Tool for High Throughput Sequence Data [Online].
```suggestion
  > Andrews, S. (2010). FastQC: A Quality Control Tool for High Throughput Sequence Data [Online].
```

2025-05-04 12:55 UTC, maxulysse approved these changes
Minor issues with conda and download, but LGTM

2025-05-05 14:31 UTC, maxulysse commented on CITATIONS.md
> +- [MultiQC](https://pubmed.ncbi.nlm.nih.gov/27312411/)
```suggestion
- [MultiQC](https://pubmed.ncbi.nlm.nih.gov/27312411/)

  > Ewels P, Magnusson M, Lundin S, Käller M. MultiQC: summarize analysis results for multiple tools and samples in a single report. Bioinformatics. 2016 Oct 1;32(19):3047-8. doi: 10.1093/bioinformatics/btw354. Epub 2016 Jun 16. PubMed PMID: 27312411; PubMed Central PMCID: PMC5039924.
```

2025-05-05 14:32 UTC, maxulysse commented on docs/output.md
>    - `*.coverage.hist.txt`: Histogram of read coverage over each chromosome
so no `<samplename>`, right?

2025-05-05 14:33 UTC, maxulysse commented on modules/local/grohmm/parametertuning/main.nf
> +    // array 10
TODO still not updated.
Not sure if you want to address that here in the code or in an issue or if you forget about this comment

2025-05-07 01:06 UTC, edmundmiller commented on docs/output.md
>    - `dragmap/`: Directory containing DRAGMAP indices.
No, I didn't bother adding the reference building since nf-core/references will be added any day now...

2025-05-07 02:39 UTC, merged